import 'package:roamly/services/user_repository.dart';

import '../models/city_entry_model.dart';
import '../models/user_model.dart';
import 'city_repository.dart';

//create mocked users to test out UI without having to manually add users
class MockUserService {
  final UserRepository userRepository;
  final CityRepository cityRepository;

  MockUserService({
    required this.userRepository,
    required this.cityRepository,
  });

  static const _demoUsers = [
    (uid: 'seed_demo_1', email: 'demo1@roamly.local', username: 'travel_lena'),   // personal / reflective
    (uid: 'seed_demo_2', email: 'demo2@roamly.local', username: 'nomad_finn'),    // humorous (chaotic)
    (uid: 'seed_demo_3', email: 'demo3@roamly.local', username: 'kai_logs'),      // short & serious
    (uid: 'seed_demo_4', email: 'demo4@roamly.local', username: 'priya_roams'),   // humorous (dry/deadpan)
    (uid: 'seed_demo_5', email: 'demo5@roamly.local', username: 'sofia_wanders'), // personal / emotional
    (uid: 'seed_demo_6', email: 'demo6@roamly.local', username: 'declan_travels'),// short & serious
  ];

  static final Map<String, List<CityEntry> Function(String, String)> _sampleEntriesByUid = {
    'seed_demo_1': _sampleEntriesFor1,
    'seed_demo_2': _sampleEntriesFor2,
    'seed_demo_3': _sampleEntriesFor3,
    'seed_demo_4': _sampleEntriesFor4,
    'seed_demo_5': _sampleEntriesFor5,
    'seed_demo_6': _sampleEntriesFor6,
  };

  Future<void> seedIfNeeded() async {
    for (final demo in _demoUsers) {
      final existing = await userRepository.getUser(demo.uid);
      if (existing != null) continue; // if already seeded, skip
      await _seedOneUser(demo.uid, demo.email, demo.username);
    }
  }

  Future<void> _seedOneUser(String uid, String email, String username) async {
    await userRepository.saveUser(UserModel(uid: uid, email: email, userName: username, profilePicturePath: null));

    final entries = _sampleEntriesByUid[uid]?.call(uid, username) ?? const [];
    for (final entry in entries) {
      await cityRepository.addEntry(entry);
    }
  }

  //Sample data generated by AI to check out UI/Not launch the App empty without posts

  // travel_lena — personal / reflective tone
  static List<CityEntry> _sampleEntriesFor1(String uid, String userName) {
    return [
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Lisbon',
        country: 'Portugal',
        continent: 'Europe',
        arrivalDate: DateTime(2026, 1, 12),
        departureDate: DateTime(2026, 1, 18),
        rating: 4.5,
        comment: 'Went alone and almost turned back at the airport. Ended up watching the sunset from Miradouro da Graça every night — still think about that light.',
        createdAt: DateTime(2026, 1, 19),
        latitude: 38.7223,
        longitude: -9.1393,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Kyoto',
        country: 'Japan',
        continent: 'Asia',
        arrivalDate: DateTime(2026, 4, 28),
        departureDate: DateTime(2026, 5, 5),
        rating: 5.0,
        comment: 'Walked through Fushimi Inari before sunrise, just me and the fog. Some trips change how you see quiet. This was one of them.',
        createdAt: DateTime(2026, 5, 6),
        latitude: 35.0116,
        longitude: 135.7681,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Copenhagen',
        country: 'Denmark',
        continent: 'Europe',
        arrivalDate: DateTime(2026, 8, 9),
        departureDate: DateTime(2026, 8, 16),
        rating: 4.0,
        comment: "Rented a bike and just followed the canals for a week. Didn't plan much and it turned out to be exactly what I needed.",
        createdAt: DateTime(2026, 8, 17),
        latitude: 55.6761,
        longitude: 12.5683,
        imagePath: null,
      ),
    ];
  }

  // nomad_finn — humorous / chaotic tone (kept as-is, just shifted into 2026)
  static List<CityEntry> _sampleEntriesFor2(String uid, String userName) {
    return [
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Venice',
        country: 'Italy',
        continent: 'Europe',
        arrivalDate: DateTime(2026, 1, 20),
        departureDate: DateTime(2026, 1, 23),
        rating: 3.5,
        comment: 'Beautiful city, but my GPS gave up after 10 minutes and just started displaying a shrug emoji. Got lost twice, proposed to a gondola out of sheer Stockholm syndrome.',
        createdAt: DateTime(2026, 1, 24),
        latitude: 45.4408,
        longitude: 12.3155,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Reykjavik',
        country: 'Iceland',
        continent: 'Europe',
        arrivalDate: DateTime(2026, 5, 11),
        departureDate: DateTime(2026, 5, 16),
        rating: 4.0,
        comment: 'Tried to see the Northern Lights. Saw a cloud. A very committed, very opaque cloud. 10/10 hot dogs though.',
        createdAt: DateTime(2026, 5, 17),
        latitude: 64.1466,
        longitude: -21.9426,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Bangkok',
        country: 'Thailand',
        continent: 'Asia',
        arrivalDate: DateTime(2026, 8, 21),
        departureDate: DateTime(2026, 8, 30),
        rating: 4.5,
        comment: 'Ordered "not spicy." The waiter looked at me with pity. He was right to. Also a monkey stole my sunglasses and honestly he looked better in them.',
        createdAt: DateTime(2026, 8, 31),
        latitude: 13.7563,
        longitude: 100.5018,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'London',
        country: 'UK',
        continent: 'Europe',
        arrivalDate: DateTime(2026, 3, 10),
        departureDate: DateTime(2026, 3, 12),
        rating: 1.5,
        comment: 'Paid £15 for a sandwich that tasted like sadness and damp cardboard. It rained so hard I think I evolved gills.',
        createdAt: DateTime(2026, 3, 13),
        latitude: 51.5074,
        longitude: -0.1278,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Pisa',
        country: 'Italy',
        continent: 'Europe',
        arrivalDate: DateTime(2026, 6, 5),
        departureDate: DateTime(2026, 6, 6),
        rating: 2.0,
        comment: 'The tower is leaning. I get it. But watching 400 people pretend to hold it up for TikTok made me want to lean into traffic.',
        createdAt: DateTime(2026, 6, 7),
        latitude: 43.7228,
        longitude: 10.4017,
      ),
    ];
  }

  // kai_logs — short & serious tone
  static List<CityEntry> _sampleEntriesFor3(String uid, String userName) {
    return [
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Marrakech',
        country: 'Morocco',
        continent: 'Africa',
        arrivalDate: DateTime(2026, 1, 8),
        departureDate: DateTime(2026, 1, 12),
        rating: 4.0,
        comment: 'Toured the medina. Hot, crowded, worth it once.',
        createdAt: DateTime(2026, 1, 13),
        latitude: 31.6295,
        longitude: -7.9811,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Prague',
        country: 'Czechia',
        continent: 'Europe',
        arrivalDate: DateTime(2026, 5, 4),
        departureDate: DateTime(2026, 5, 8),
        rating: 4.5,
        comment: 'Castle district in the morning avoids the crowds. Good beer, average food.',
        createdAt: DateTime(2026, 5, 9),
        latitude: 50.0755,
        longitude: 14.4378,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Seoul',
        country: 'South Korea',
        continent: 'Asia',
        arrivalDate: DateTime(2026, 8, 3),
        departureDate: DateTime(2026, 8, 9),
        rating: 5.0,
        comment: 'Efficient public transit. Would return for the food alone.',
        createdAt: DateTime(2026, 8, 10),
        latitude: 37.5665,
        longitude: 126.9780,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Brussels',
        country: 'Belgium',
        continent: 'Europe',
        arrivalDate: DateTime(2026, 2, 20),
        departureDate: DateTime(2026, 2, 22),
        rating: 1.0,
        comment: 'Construction everywhere, extremely rude service at the hotel, and half the landmarks were covered in scaffolding. Total waste of a weekend.',
        createdAt: DateTime(2026, 2, 23),
        latitude: 50.8503,
        longitude: 4.3517,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Las Vegas',
        country: 'USA',
        continent: 'North America',
        arrivalDate: DateTime(2026, 7, 12),
        departureDate: DateTime(2026, 7, 14),
        rating: 1.5,
        comment: 'Too loud, too expensive, and smells like stale cigarettes and desperation. Not my kind of travel at all.',
        createdAt: DateTime(2026, 7, 15),
        latitude: 36.1716,
        longitude: -115.1391,
      ),
    ];
  }

  // priya_roams — humorous / dry & deadpan tone
  static List<CityEntry> _sampleEntriesFor4(String uid, String userName) {
    return [
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Mexico City',
        country: 'Mexico',
        continent: 'North America',
        arrivalDate: DateTime(2026, 2, 2),
        departureDate: DateTime(2026, 2, 8),
        rating: 4.5,
        comment: "Ordered tacos al pastor at 2am from a stranger's kitchen window. No regrets. My cardiologist has some, allegedly.",
        createdAt: DateTime(2026, 2, 9),
        latitude: 19.4326,
        longitude: -99.1332,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Dublin',
        country: 'Ireland',
        continent: 'Europe',
        arrivalDate: DateTime(2026, 5, 25),
        departureDate: DateTime(2026, 5, 29),
        rating: 4.0,
        comment: "Went into a pub 'for one drink.' Emerged four hours later with a new best friend named Sean and no memory of his last name.",
        createdAt: DateTime(2026, 5, 30),
        latitude: 53.3498,
        longitude: -6.2603,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Cape Town',
        country: 'South Africa',
        continent: 'Africa',
        arrivalDate: DateTime(2026, 8, 14),
        departureDate: DateTime(2026, 8, 20),
        rating: 4.5,
        comment: 'Hiked Table Mountain. The mountain won. I now respect cable cars as a legitimate life choice.',
        createdAt: DateTime(2026, 8, 21),
        latitude: -33.9249,
        longitude: 18.4241,
        imagePath: null,
      ),
    ];
  }

  // sofia_wanders — personal / emotional tone
  static List<CityEntry> _sampleEntriesFor5(String uid, String userName) {
    return [
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Paris',
        country: 'France',
        continent: 'Europe',
        arrivalDate: DateTime(2026, 1, 15),
        departureDate: DateTime(2026, 1, 20),
        rating: 4.5,
        comment: 'Went back to the café where my grandmother used to write letters. Sat there for two hours doing nothing but thinking about her.',
        createdAt: DateTime(2026, 1, 21),
        latitude: 48.8566,
        longitude: 2.3522,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Istanbul',
        country: 'Turkey',
        continent: 'Europe',
        arrivalDate: DateTime(2026, 5, 18),
        departureDate: DateTime(2026, 5, 24),
        rating: 5.0,
        comment: "Got lost in the Grand Bazaar and teared up a little from how alive it all felt. Hard to explain unless you've been.",
        createdAt: DateTime(2026, 5, 25),
        latitude: 41.0082,
        longitude: 28.9784,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Buenos Aires',
        country: 'Argentina',
        continent: 'South America',
        arrivalDate: DateTime(2026, 8, 6),
        departureDate: DateTime(2026, 8, 13),
        rating: 4.5,
        comment: "Danced tango with a stranger in a plaza at midnight. Felt like the most myself I've been in years.",
        createdAt: DateTime(2026, 8, 14),
        latitude: -34.6037,
        longitude: -58.3816,
        imagePath: null,
      ),
    ];
  }

  // declan_travels — short & serious tone
  static List<CityEntry> _sampleEntriesFor6(String uid, String userName) {
    return [
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Vienna',
        country: 'Austria',
        continent: 'Europe',
        arrivalDate: DateTime(2026, 1, 26),
        departureDate: DateTime(2026, 1, 30),
        rating: 4.0,
        comment: 'Museums are excellent. City is expensive. Budget accordingly.',
        createdAt: DateTime(2026, 1, 31),
        latitude: 48.2082,
        longitude: 16.3738,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Nairobi',
        country: 'Kenya',
        continent: 'Africa',
        arrivalDate: DateTime(2026, 5, 7),
        departureDate: DateTime(2026, 5, 12),
        rating: 4.5,
        comment: 'Safari day trip recommended. Book through a licensed operator.',
        createdAt: DateTime(2026, 5, 13),
        latitude: -1.2921,
        longitude: 36.8219,
        imagePath: null,
      ),
      CityEntry(
        id: CityEntry.UNSAVED_ID,
        userId: uid,
        userName: userName,
        name: 'Singapore',
        country: 'Singapore',
        continent: 'Asia',
        arrivalDate: DateTime(2026, 8, 17),
        departureDate: DateTime(2026, 8, 21),
        rating: 4.0,
        comment: 'Clean, efficient, strict rules. Followed them. No issues.',
        createdAt: DateTime(2026, 8, 22),
        latitude: 1.3521,
        longitude: 103.8198,
        imagePath: null,
      ),
    ];
  }
}