// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_7B1B5mrvjgwsnX9AHFcZCPisZXy-bqY',
    appId: '1:93379427351:web:ecb62a34555f28fabcf052',
    messagingSenderId: '93379427351',
    projectId: 'roamly-8e766',
    authDomain: 'roamly-8e766.firebaseapp.com',
    storageBucket: 'roamly-8e766.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0rXAAt-UGyzARj3UczP0oM68bF2VAfw0',
    appId: '1:93379427351:android:5979bf87edc87a8ebcf052',
    messagingSenderId: '93379427351',
    projectId: 'roamly-8e766',
    storageBucket: 'roamly-8e766.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoaHn9Bi69tZl-YkssCH_I7Dlkb_1pK5Y',
    appId: '1:93379427351:ios:b5ed3a10d7ca9808bcf052',
    messagingSenderId: '93379427351',
    projectId: 'roamly-8e766',
    storageBucket: 'roamly-8e766.firebasestorage.app',
    iosBundleId: 'com.example.roamly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoaHn9Bi69tZl-YkssCH_I7Dlkb_1pK5Y',
    appId: '1:93379427351:ios:b5ed3a10d7ca9808bcf052',
    messagingSenderId: '93379427351',
    projectId: 'roamly-8e766',
    storageBucket: 'roamly-8e766.firebasestorage.app',
    iosBundleId: 'com.example.roamly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_7B1B5mrvjgwsnX9AHFcZCPisZXy-bqY',
    appId: '1:93379427351:web:fb58dac8ec3d64e7bcf052',
    messagingSenderId: '93379427351',
    projectId: 'roamly-8e766',
    authDomain: 'roamly-8e766.firebaseapp.com',
    storageBucket: 'roamly-8e766.firebasestorage.app',
  );
}
